name: Wulfpack
favicon: null
layout_spectrum: 0.46027
typography_spectrum: 0.74021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2f7'
    - '#1e111a'
    - '#b3b5b4'
    - '#584f50'
    - '#6e7d7a'
  brandStrength: 0.375
  lightness: 0.9933196811471134
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
