name: Wulfpack
favicon: null
layout_spectrum: 0.057990563567727804
typography_spectrum: 0.7088337843306363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25306905107572675
  lightness: 0.9933196811471134
  saturation: 0.5688322936184704
  rhythmicContrast: 0.04628787934780121
purpose: []
